# Generated by Django 4.2.16 on 2024-10-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praoannons',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to='prao_annonsbilder/'),
        ),
    ]
