# Generated by Django 4.2.16 on 2024-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktik', '0003_praoannons_annons_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praoannons',
            name='annons_typ',
            field=models.CharField(choices=[('apl', 'APL'), ('praktik', 'Praktik'), ('prao', 'Prao')], max_length=10),
        ),
    ]
