# Generated by Django 4.2.16 on 2024-11-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktik', '0004_alter_praoannons_annons_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='praoannons',
            name='bransch_typ',
            field=models.CharField(choices=[('teknik', 'Teknik'), ('vård', 'Vård'), ('handel', 'Handel'), ('service', 'Service'), ('fordon', 'Fordon')], default='Okänd', max_length=10),
        ),
    ]
