# Generated by Django 4.2.16 on 2024-11-20 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('praktik', '0005_praoannons_bransch_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praoannons',
            name='bransch_typ',
            field=models.CharField(choices=[('teknik', 'Teknik'), ('vård', 'Vård'), ('handel', 'Handel'), ('service', 'Service'), ('fordon', 'Fordon'), ('industri', 'Industri')], default='Okänd', max_length=10),
        ),
        migrations.CreateModel(
            name='Nyhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beskrivning', models.TextField()),
                ('publicerad_datum', models.DateTimeField(auto_now_add=True)),
                ('bild', models.ImageField(blank=True, null=True, upload_to='nyhetsbilder/')),
                ('användare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
