# Generated by Django 4.2.16 on 2024-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktik', '0007_praoannons_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='praoannons',
            name='org_nummer',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
