# Generated by Django 4.2.16 on 2024-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praktik', '0006_alter_praoannons_bransch_typ_nyhet'),
    ]

    operations = [
        migrations.AddField(
            model_name='praoannons',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
